// GENERATED CODE — DO NOT MODIFY BY HAND.
// This file is regenerated by `fluent_gen` whenever the source FTL files change.
//
// Run `dart run build_runner build` to refresh after edits.

import 'package:fluent_bundle/fluent_bundle.dart';

/// Typed accessor for fluent_bundle messages. Wraps a [FluentBundle] and exposes one method per message + per attribute, with parameter types inferred from how each variable is used in the FTL source.
///
/// Construct with the bundle the consumer prepared (loaded with the active locale's FTL):
///
/// ```dart
/// final bundle = FluentBundle('en')..addResource(ftl);
/// final t = Translations(bundle);
/// final hi = t.welcome(name: "Aria");
/// ```
class Translations {
  /// Wraps the prepared [FluentBundle].
  Translations(this._bundle);

  final FluentBundle _bundle;

  /// ```ftl
  /// login = Sign in
  ///     .title = Welcome back
  ///     .helper = Tap to continue
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:1`.
  String login({List<FluentError>? errors}) =>
      _bundle.formatMessage('login', args: <String, Object?>{}, errors: errors);

  /// ```ftl
  /// login = Sign in
  ///     .title = Welcome back
  ///     .helper = Tap to continue
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:2`.
  String login$title({List<FluentError>? errors}) => _bundle.formatMessage(
    'login',
    attribute: 'title',
    args: <String, Object?>{},
    errors: errors,
  );

  /// ```ftl
  /// login = Sign in
  ///     .title = Welcome back
  ///     .helper = Tap to continue
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:3`.
  String login$helper({List<FluentError>? errors}) => _bundle.formatMessage(
    'login',
    attribute: 'helper',
    args: <String, Object?>{},
    errors: errors,
  );

  /// ```ftl
  /// shortcut =
  ///     .key = Ctrl+S
  ///     .description = Save the current document
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:6`.
  String shortcut$key({List<FluentError>? errors}) => _bundle.formatMessage(
    'shortcut',
    attribute: 'key',
    args: <String, Object?>{},
    errors: errors,
  );

  /// ```ftl
  /// shortcut =
  ///     .key = Ctrl+S
  ///     .description = Save the current document
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:7`.
  String shortcut$description({List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'shortcut',
        attribute: 'description',
        args: <String, Object?>{},
        errors: errors,
      );

  /// Every generated accessor name, for tooling (the
  /// unused-message helper in
  /// `package:fluent_gen/testing.dart`).
  static const List<String> accessorNames = [
    r'login',
    r'login$title',
    r'login$helper',
    r'shortcut$key',
    r'shortcut$description',
  ];
}

/// Every locale the generator discovered under the FTL
/// directory. Pure Dart — parse and negotiate locale tags
/// without any UI framework.
enum AppLocale {
  /// `en`.
  en('en');

  const AppLocale(this.languageTag);

  /// The locale tag as discovered from the FTL layout.
  final String languageTag;

  /// The generator's base locale — codegen was driven by it,
  /// so it is always fully covered.
  static const AppLocale base = AppLocale.en;

  /// The value whose tag matches [tag] (case-insensitive),
  /// or null.
  static AppLocale? tryParse(String tag) {
    final lower = tag.toLowerCase();
    for (final locale in values) {
      if (locale.languageTag.toLowerCase() == lower) {
        return locale;
      }
    }
    return null;
  }

  /// Best available match for a requested tag, resolved
  /// through the family ladder (fluent_bundle's
  /// `negotiateLocale`): exact match, then the tag
  /// progressively truncated, then the most general
  /// available tag sharing the requested language; then
  /// [fallback], defaulting to [base].
  static AppLocale negotiate(String requested, {AppLocale? fallback}) {
    final match = negotiateLocale(
      requested,
      available: [for (final locale in values) locale.languageTag],
    );
    if (match == null) return fallback ?? base;
    return tryParse(match) ?? fallback ?? base;
  }
}
