// GENERATED CODE — DO NOT MODIFY BY HAND.
// This file is regenerated by `fluent_gen` whenever the source FTL files change.
//
// Run `dart run build_runner build` to refresh after edits.

import 'package:fluent_bundle/fluent_bundle.dart';

/// Typed accessor for fluent_bundle messages. Wraps a [FluentBundle] and exposes one method per message + per attribute, with parameter types inferred from how each variable is used in the FTL source.
///
/// Construct with the bundle the consumer prepared (loaded with the active locale's FTL):
///
/// ```dart
/// final bundle = FluentBundle('en')..addResource(ftl);
/// final t = Translations(bundle);
/// final hi = t.welcome(name: "Aria");
/// ```
class Translations {
  /// Wraps the prepared [FluentBundle].
  Translations(this._bundle);

  final FluentBundle _bundle;

  /// ```ftl
  /// hello = Hi
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:1`.
  String hello({List<FluentError>? errors}) =>
      _bundle.formatMessage('hello', args: <String, Object?>{}, errors: errors);

  /// ```ftl
  /// welcome = Hello, { $name }!
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:2`.
  String welcome({required Object? name, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'welcome',
        args: <String, Object?>{'name': name},
        errors: errors,
      );

  /// ```ftl
  /// items = You have { $count ->
  ///     [one] one new message
  ///    *[other] { $count } new messages
  /// }.
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:3`.
  String items({required num count, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'items',
        args: <String, Object?>{'count': count},
        errors: errors,
      );

  /// ```ftl
  /// price = Total: { NUMBER($amount) }
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:7`.
  String price({required num amount, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'price',
        args: <String, Object?>{'amount': amount},
        errors: errors,
      );

  /// ```ftl
  /// launchedAt = Launched at { DATETIME($d) }
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:8`.
  String launchedAt({required DateTime d, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'launchedAt',
        args: <String, Object?>{'d': d},
        errors: errors,
      );

  /// Every generated accessor name, for tooling (the
  /// unused-message helper in
  /// `package:fluent_gen/testing.dart`).
  static const List<String> accessorNames = [
    r'hello',
    r'welcome',
    r'items',
    r'price',
    r'launchedAt',
  ];
}

/// Every locale the generator discovered under the FTL
/// directory. Pure Dart — parse and negotiate locale tags
/// without any UI framework.
enum AppLocale {
  /// `en`.
  en('en');

  const AppLocale(this.languageTag);

  /// The locale tag as discovered from the FTL layout.
  final String languageTag;

  /// The generator's base locale — codegen was driven by it,
  /// so it is always fully covered.
  static const AppLocale base = AppLocale.en;

  /// The value whose tag matches [tag] (case-insensitive),
  /// or null.
  static AppLocale? tryParse(String tag) {
    final lower = tag.toLowerCase();
    for (final locale in values) {
      if (locale.languageTag.toLowerCase() == lower) {
        return locale;
      }
    }
    return null;
  }

  /// Best available match for a requested tag, resolved
  /// through the family ladder (fluent_bundle's
  /// `negotiateLocale`): exact match, then the tag
  /// progressively truncated, then the most general
  /// available tag sharing the requested language; then
  /// [fallback], defaulting to [base].
  static AppLocale negotiate(String requested, {AppLocale? fallback}) {
    final match = negotiateLocale(
      requested,
      available: [for (final locale in values) locale.languageTag],
    );
    if (match == null) return fallback ?? base;
    return tryParse(match) ?? fallback ?? base;
  }
}
