// GENERATED CODE — DO NOT MODIFY BY HAND.
// This file is regenerated by `fluent_gen` whenever the source FTL files change.
//
// Run `dart run build_runner build` to refresh after edits.

import 'package:fluent_bundle/fluent_bundle.dart';
import 'package:fluent_bundle/markup.dart';

/// Typed accessor for fluent_bundle messages. Wraps a [FluentBundle] and exposes one method per message + per attribute, with parameter types inferred from how each variable is used in the FTL source.
///
/// Construct with the bundle the consumer prepared (loaded with the active locale's FTL):
///
/// ```dart
/// final bundle = FluentBundle('en')..addResource(ftl);
/// final t = Translations(bundle);
/// final hi = t.welcome(name: "Aria");
/// ```
class Translations {
  /// Wraps the prepared [FluentBundle].
  Translations(this._bundle);

  final FluentBundle _bundle;

  /// ```ftl
  /// welcome = Hello, <bold>{ $name }</bold>!
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:1`.
  ///
  /// Has inline markup — for a span-tree variant suitable for `RichText`, see [welcomeAsSpans].
  String welcome({required Object? name, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'welcome',
        args: <String, Object?>{'name': name},
        errors: errors,
      );

  /// ```ftl
  /// welcome = Hello, <bold>{ $name }</bold>!
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:1`.
  ///
  /// Returns the span tree. For the resolved-string variant see [welcome].
  List<FluentSpan> welcomeAsSpans({
    required Object? name,
    List<FluentError>? errors,
  }) => _bundle.formatMessageAsSpans(
    'welcome',
    args: <String, Object?>{'name': name},
    errors: errors,
  );

  /// ```ftl
  /// help = Read <a href="/help">our help</a>.
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:2`.
  ///
  /// Has inline markup — for a span-tree variant suitable for `RichText`, see [helpAsSpans].
  String help({List<FluentError>? errors}) =>
      _bundle.formatMessage('help', args: <String, Object?>{}, errors: errors);

  /// ```ftl
  /// help = Read <a href="/help">our help</a>.
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:2`.
  ///
  /// Returns the span tree. For the resolved-string variant see [help].
  List<FluentSpan> helpAsSpans({List<FluentError>? errors}) => _bundle
      .formatMessageAsSpans('help', args: <String, Object?>{}, errors: errors);

  /// ```ftl
  /// tip = Save with <icon name="floppy"/>.
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:3`.
  ///
  /// Has inline markup — for a span-tree variant suitable for `RichText`, see [tipAsSpans].
  String tip({List<FluentError>? errors}) =>
      _bundle.formatMessage('tip', args: <String, Object?>{}, errors: errors);

  /// ```ftl
  /// tip = Save with <icon name="floppy"/>.
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:3`.
  ///
  /// Returns the span tree. For the resolved-string variant see [tip].
  List<FluentSpan> tipAsSpans({List<FluentError>? errors}) => _bundle
      .formatMessageAsSpans('tip', args: <String, Object?>{}, errors: errors);

  /// Every generated accessor name, for tooling (the
  /// unused-message helper in
  /// `package:fluent_gen/testing.dart`).
  static const List<String> accessorNames = [
    r'welcome',
    r'welcomeAsSpans',
    r'help',
    r'helpAsSpans',
    r'tip',
    r'tipAsSpans',
  ];
}

/// Every locale the generator discovered under the FTL
/// directory. Pure Dart — parse and negotiate locale tags
/// without any UI framework.
enum AppLocale {
  /// `en`.
  en('en');

  const AppLocale(this.languageTag);

  /// The locale tag as discovered from the FTL layout.
  final String languageTag;

  /// The generator's base locale — codegen was driven by it,
  /// so it is always fully covered.
  static const AppLocale base = AppLocale.en;

  /// The value whose tag matches [tag] (case-insensitive),
  /// or null.
  static AppLocale? tryParse(String tag) {
    final lower = tag.toLowerCase();
    for (final locale in values) {
      if (locale.languageTag.toLowerCase() == lower) {
        return locale;
      }
    }
    return null;
  }

  /// Best available match for a requested tag, resolved
  /// through the family ladder (fluent_bundle's
  /// `negotiateLocale`): exact match, then the tag
  /// progressively truncated, then the most general
  /// available tag sharing the requested language; then
  /// [fallback], defaulting to [base].
  static AppLocale negotiate(String requested, {AppLocale? fallback}) {
    final match = negotiateLocale(
      requested,
      available: [for (final locale in values) locale.languageTag],
    );
    if (match == null) return fallback ?? base;
    return tryParse(match) ?? fallback ?? base;
  }
}
