// GENERATED CODE — DO NOT MODIFY BY HAND.
// This file is regenerated by `fluent_gen` whenever the source FTL files change.
//
// Run `dart run build_runner build` to refresh after edits.

import 'package:fluent_bundle/fluent_bundle.dart';
import 'package:fluent_bundle/markup.dart';

/// Typed accessor for fluent_bundle messages. Wraps a [FluentBundle] and exposes one method per message + per attribute, with parameter types inferred from how each variable is used in the FTL source.
///
/// Construct with the bundle the consumer prepared (loaded with the active locale's FTL):
///
/// ```dart
/// final bundle = FluentBundle('en')..addResource(ftl);
/// final t = AppMessages(bundle);
/// final hi = t.welcome(name: "Aria");
/// ```
class AppMessages {
  /// Wraps the prepared [FluentBundle].
  AppMessages(this._bundle);

  final FluentBundle _bundle;

  /// ```ftl
  /// hello = Hi
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:6`.
  String hello({List<FluentError>? errors}) =>
      _bundle.formatMessage('hello', args: <String, Object?>{}, errors: errors);

  /// A comment type pin: usage alone leaves $name as Object?, and the
  /// `(String)` annotation narrows it.
  /// $name (String) - the person to greet.
  ///
  /// ```ftl
  /// # A comment type pin: usage alone leaves $name as Object?, and the
  /// # `(String)` annotation narrows it.
  /// # $name (String) - the person to greet.
  /// welcome = Hello, { $name }!
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:8`.
  String welcome({required String name, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'welcome',
        args: <String, Object?>{'name': name},
        errors: errors,
      );

  /// ```ftl
  /// items = You have { $count ->
  ///     [one] one new message
  ///    *[other] { $count } new messages
  /// }.
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:13`.
  String items({required num count, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'items',
        args: <String, Object?>{'count': count},
        errors: errors,
      );

  /// A string selector — its default is *[other], but the non-plural
  /// keys make it a String, not a num.
  ///
  /// ```ftl
  /// # A string selector — its default is *[other], but the non-plural
  /// # keys make it a String, not a num.
  /// device = Open the { $platform ->
  ///     [ios] App Store
  ///     [android] Play Store
  ///    *[other] store
  /// }.
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:18`.
  String device({required String platform, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'device',
        args: <String, Object?>{'platform': platform},
        errors: errors,
      );

  /// ```ftl
  /// price = Total: { NUMBER($amount, style: "currency", currency: "USD") }
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:26`.
  String price({required num amount, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'price',
        args: <String, Object?>{'amount': amount},
        errors: errors,
      );

  /// ```ftl
  /// launchedAt = Launched at { DATETIME($d, dateStyle: "medium") }
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:27`.
  String launchedAt({required DateTime d, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'launchedAt',
        args: <String, Object?>{'d': d},
        errors: errors,
      );

  /// Inline markup — generates an AsSpans sibling.
  ///
  /// ```ftl
  /// # Inline markup — generates an AsSpans sibling.
  /// banner = Read <bold>{ $title }</bold> on our blog.
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:29`.
  ///
  /// Has inline markup — for a span-tree variant suitable for `RichText`, see [bannerAsSpans].
  String banner({required Object? title, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'banner',
        args: <String, Object?>{'title': title},
        errors: errors,
      );

  /// Inline markup — generates an AsSpans sibling.
  ///
  /// ```ftl
  /// # Inline markup — generates an AsSpans sibling.
  /// banner = Read <bold>{ $title }</bold> on our blog.
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:29`.
  ///
  /// Returns the span tree. For the resolved-string variant see [banner].
  List<FluentSpan> bannerAsSpans({
    required Object? title,
    List<FluentError>? errors,
  }) => _bundle.formatMessageAsSpans(
    'banner',
    args: <String, Object?>{'title': title},
    errors: errors,
  );

  /// A transitive message reference: greeting supplies $name, so the
  /// generated welcomeBack takes both $name and $when.
  ///
  /// ```ftl
  /// # A transitive message reference: greeting supplies $name, so the
  /// # generated welcomeBack takes both $name and $when.
  /// greeting = Hi again, { $name }
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:32`.
  String greeting({required Object? name, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'greeting',
        args: <String, Object?>{'name': name},
        errors: errors,
      );

  /// ```ftl
  /// welcomeBack = { greeting } — last seen { DATETIME($when, dateStyle: "short") }
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:35`.
  String welcomeBack({
    required Object? name,
    required DateTime $when,
    List<FluentError>? errors,
  }) => _bundle.formatMessage(
    'welcomeBack',
    args: <String, Object?>{'name': name, 'when': $when},
    errors: errors,
  );

  /// Attributes — emit per-attribute methods, each demanding only its
  /// own pattern's variables.
  ///
  /// ```ftl
  /// # Attributes — emit per-attribute methods, each demanding only its
  /// # own pattern's variables.
  /// login = Sign in
  ///     .title = Welcome back
  ///     .helper = Tap to continue, { $name }
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:37`.
  String login({List<FluentError>? errors}) =>
      _bundle.formatMessage('login', args: <String, Object?>{}, errors: errors);

  /// Attributes — emit per-attribute methods, each demanding only its
  /// own pattern's variables.
  ///
  /// ```ftl
  /// # Attributes — emit per-attribute methods, each demanding only its
  /// # own pattern's variables.
  /// login = Sign in
  ///     .title = Welcome back
  ///     .helper = Tap to continue, { $name }
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:40`.
  String login$title({List<FluentError>? errors}) => _bundle.formatMessage(
    'login',
    attribute: 'title',
    args: <String, Object?>{},
    errors: errors,
  );

  /// Attributes — emit per-attribute methods, each demanding only its
  /// own pattern's variables.
  ///
  /// ```ftl
  /// # Attributes — emit per-attribute methods, each demanding only its
  /// # own pattern's variables.
  /// login = Sign in
  ///     .title = Welcome back
  ///     .helper = Tap to continue, { $name }
  /// ```
  ///
  /// Source: `lib/i18n/en.ftl:41`.
  String login$helper({required Object? name, List<FluentError>? errors}) =>
      _bundle.formatMessage(
        'login',
        attribute: 'helper',
        args: <String, Object?>{'name': name},
        errors: errors,
      );

  /// Every generated accessor name, for tooling (the
  /// unused-message helper in
  /// `package:fluent_gen/testing.dart`).
  static const List<String> accessorNames = [
    r'hello',
    r'welcome',
    r'items',
    r'device',
    r'price',
    r'launchedAt',
    r'banner',
    r'bannerAsSpans',
    r'greeting',
    r'welcomeBack',
    r'login',
    r'login$title',
    r'login$helper',
  ];
}

/// Every locale the generator discovered under the FTL
/// directory. Pure Dart — parse and negotiate locale tags
/// without any UI framework.
enum AppLocale {
  /// `en`.
  en('en'),

  /// `fr`.
  fr('fr');

  const AppLocale(this.languageTag);

  /// The locale tag as discovered from the FTL layout.
  final String languageTag;

  /// The generator's base locale — codegen was driven by it,
  /// so it is always fully covered.
  static const AppLocale base = AppLocale.en;

  /// The value whose tag matches [tag] (case-insensitive),
  /// or null.
  static AppLocale? tryParse(String tag) {
    final lower = tag.toLowerCase();
    for (final locale in values) {
      if (locale.languageTag.toLowerCase() == lower) {
        return locale;
      }
    }
    return null;
  }

  /// Best available match for a requested tag, resolved
  /// through the family ladder (fluent_bundle's
  /// `negotiateLocale`): exact match, then the tag
  /// progressively truncated, then the most general
  /// available tag sharing the requested language; then
  /// [fallback], defaulting to [base].
  static AppLocale negotiate(String requested, {AppLocale? fallback}) {
    final match = negotiateLocale(
      requested,
      available: [for (final locale in values) locale.languageTag],
    );
    if (match == null) return fallback ?? base;
    return tryParse(match) ?? fallback ?? base;
  }

  /// This locale's embedded FTL sources, one per file, in
  /// discovery order. Baked in at build time — no asset
  /// pipeline, no async load.
  List<String> get ftlSources => switch (this) {
    AppLocale.en => const [
      '''
# Base-locale fixture. Every shape the generator supports appears at
# least once: plain message, NUMBER, DATETIME, plural selector, string
# selector, attributes, inline markup, transitive message references,
# and a comment type pin.

hello = Hi

# A comment type pin: usage alone leaves \$name as Object?, and the
# `(String)` annotation narrows it.
# \$name (String) - the person to greet.
welcome = Hello, { \$name }!

items = You have { \$count ->
    [one] one new message
   *[other] { \$count } new messages
}.

# A string selector — its default is *[other], but the non-plural
# keys make it a String, not a num.
device = Open the { \$platform ->
    [ios] App Store
    [android] Play Store
   *[other] store
}.

price = Total: { NUMBER(\$amount, style: "currency", currency: "USD") }
launchedAt = Launched at { DATETIME(\$d, dateStyle: "medium") }

# Inline markup — generates an AsSpans sibling.
banner = Read <bold>{ \$title }</bold> on our blog.

# A transitive message reference: greeting supplies \$name, so the
# generated welcomeBack takes both \$name and \$when.
greeting = Hi again, { \$name }
welcomeBack = { greeting } — last seen { DATETIME(\$when, dateStyle: "short") }

# Attributes — emit per-attribute methods, each demanding only its
# own pattern's variables.
login = Sign in
    .title = Welcome back
    .helper = Tap to continue, { \$name }
''',
    ],
    AppLocale.fr => const [
      '''
# Non-base locale — partial coverage by design. The validator
# will warn about the gaps; the build should still succeed.

hello = Salut
welcome = Bonjour, { \$name } !
items = Vous avez { \$count ->
    [one] un nouveau message
   *[other] { \$count } nouveaux messages
}.
# `price`, `launchedAt`, `banner`, and `login.*` deliberately
# omitted — surfaces missing-message warnings.

# `bonjour` deliberately invented — surfaces an orphan-message
# warning.
bonjour = Bonjour le monde
''',
    ],
  };

  /// A ready bundle for this locale: every embedded source
  /// added, formatting delegated to [backend] (pass an
  /// `IcuBackend` / `IntlBackend` from a satellite package
  /// for CLDR-aware output).
  FluentBundle load({FluentBackend backend = const FluentBackend()}) {
    final bundle = FluentBundle(languageTag, backend: backend);
    for (final source in ftlSources) {
      bundle.addResource(source);
    }
    return bundle;
  }
}
